name: autocenter_app
description: Auto Center Pre-Service App
publish_to: 'none'

version: 1.1.38+61

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Architecture
  provider: ^6.1.2
  get_it: ^8.0.0
  
  # Networking
  dio: ^5.4.3
  dio_smart_retry: ^6.0.0

  # UI Transitions & Loading
  shimmer: ^3.0.0

  # Offline persistence & Cache
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0
  
  # Background sync
  workmanager: ^0.9.0+3

  # Image processing
  camera: ^0.11.0
  image_picker: ^1.1.0
  flutter_image_compress: ^2.3.0
  google_fonts: ^8.1.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.0.5

  # Thermal Printing / Sharing Option B
  share_plus: ^10.1.0
  intl: ^0.19.0
  pdf: ^3.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/coliseu_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/coliseu_icon.png"
