SELECT FIRST 10 ID_CLIENTE, NOME, NOME_FANTASIA, CPF_CNPJ, DATA_CADASTRO, AN_INATIVO FROM CLIENTES;
SELECT FIRST 10 ID_PEDIDO, TIPO, STATUS, VALOR_PEDIDO, DATA_HORA FROM PEDIDOS;
SELECT FIRST 10 ID_ITEM, ID_PEDIDO, ID_PRODUTO, QTDE, VALOR_UNITARIO, VALOR_TOTAL FROM PEDIDO_ITENS;
SELECT FIRST 10 ID_CONTA, TIPO, VALOR_CALC, BAIXA FROM MOB_LISTACONTAS;
