@echo off
echo Parando o servico do Worker...
net stop "ColiseuSalesWorker_Piveta"
echo Copiando novos binarios do Worker...
xcopy /Y /E /I "C:\Users\rober\.gemini\antigravity\scratch\Coliseu_Sales\worker\bin\Release\net8.0-windows\win-x64\publish\*" "C:\Sales\"
echo Copiando o Configurador v2.5.54...
copy /Y "C:\Users\rober\.gemini\antigravity\scratch\Coliseu_Sales\ColiseuSales.Configurator_v2.5.54.exe" "C:\Sales\ColiseuSales.Configurator.exe"
copy /Y "C:\Users\rober\.gemini\antigravity\scratch\Coliseu_Sales\ColiseuSales.Configurator_v2.5.54.exe" "C:\Sales\ColiseuSales.Configurator_v2.5.54.exe"
echo Iniciando o servico do Worker...
net start "ColiseuSalesWorker_Piveta"
pause
