// <auto-generated />
using System;
using Coliseu.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coliseu.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260615182700_AddPartnersAndRequests")]
    partial class AddPartnersAndRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<Guid?>("PermissionGroupId");

                    b.Property<int>("Role");

                    b.Property<bool>("TotpEnabled");

                    b.Property<string>("TotpSecretEncrypted");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("AdminEmail")
                        .HasMaxLength(200);

                    b.Property<Guid?>("CompanyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Details")
                        .HasMaxLength(2000);

                    b.Property<Guid?>("DeviceId");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45);

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("AdminEmail");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20);

                    b.Property<Guid>("CompanyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("ErpCentroPadrao")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("ErpDeptoPadrao")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("ErpEmpresaId");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Status");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("IX_branches_DefaultBranch")
                        .HasFilter("\"IsDefault\" = true");

                    b.HasIndex("CompanyId", "ErpEmpresaId")
                        .IsUnique()
                        .HasDatabaseName("IX_branches_CompanyId_ErpEmpresaId");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<bool>("AllowNegativeStock");

                    b.Property<string>("CompanyKeyEncrypted");

                    b.Property<string>("CompanyKeyHash")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("ContactEmail");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("DeviceLimit");

                    b.Property<string>("FirebirdDatabasePath")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("FirebirdHost")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("FirebirdPasswordEncrypted")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("FirebirdUser")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LogoBase64");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("PriceTableMode")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CompanyKeyHash")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.CompanyModule", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("ApiKeyEncrypted");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<Guid>("CompanyId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("DeviceLimit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("MiddlewareBaseUrl")
                        .HasMaxLength(500);

                    b.Property<string>("ModuleSlug")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .HasDatabaseName("IX_company_modules_ApiKeyHash");

                    b.HasIndex("CompanyId", "ModuleSlug")
                        .IsUnique()
                        .HasDatabaseName("IX_company_modules_CompanyId_ModuleSlug");

                    b.ToTable("company_modules", (string)null);
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("ActivationKey")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50);

                    b.Property<Guid>("CompanyId");

                    b.Property<string>("DeviceUuid")
                        .HasMaxLength(255);

                    b.Property<DateTime>("FirstActivation");

                    b.Property<DateTime>("LastAccess");

                    b.Property<string>("Model")
                        .HasMaxLength(200);

                    b.Property<string>("ModuleSlug")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasDefaultValue("coliseu-sales");

                    b.Property<string>("Name")
                        .HasMaxLength(150);

                    b.Property<string>("OS")
                        .HasMaxLength(100);

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("ActivationKey")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.HasIndex("ModuleSlug");

                    b.HasIndex("DeviceUuid", "CompanyId", "ModuleSlug")
                        .HasDatabaseName("IX_devices_DeviceUuid_CompanyId_Module")
                        .HasFilter("\"DeviceUuid\" IS NOT NULL");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.LicenseRequest", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<bool>("AllowNegativeStock")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("BranchesJson");

                    b.Property<string>("ClientCnpj")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ClientCompanyType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid?>("CompanyId");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(50);

                    b.Property<string>("DeptCode")
                        .HasMaxLength(50);

                    b.Property<string>("FirebirdDatabasePath")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("FirebirdHost")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("FirebirdPasswordEncrypted")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("FirebirdUser")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000);

                    b.Property<Guid>("PartnerId");

                    b.Property<string>("PriceTableMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasDefaultValue("none");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("RequestedAt");

                    b.Property<Guid?>("RequestedByAdminId");

                    b.Property<DateTime?>("ReviewedAt");

                    b.Property<Guid?>("ReviewedByAdminId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("ClientCnpj");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("Status");

                    b.ToTable("license_requests", (string)null);
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.LicenseRequestModule", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("DeviceLimit");

                    b.Property<Guid>("LicenseRequestId");

                    b.Property<string>("ModuleSlug")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("LicenseRequestId");

                    b.HasIndex("LicenseRequestId", "ModuleSlug")
                        .IsUnique();

                    b.ToTable("license_request_modules", (string)null);
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("permission_groups", (string)null);
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<Guid>("DeviceId");

                    b.Property<DateTime>("ExpiresAt");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.AdminUser", b =>
                {
                    b.HasOne("Coliseu.Identity.Domain.Entities.PermissionGroup", "PermissionGroup")
                        .WithMany("Users")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.Branch", b =>
                {
                    b.HasOne("Coliseu.Identity.Domain.Entities.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.CompanyModule", b =>
                {
                    b.HasOne("Coliseu.Identity.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.Device", b =>
                {
                    b.HasOne("Coliseu.Identity.Domain.Entities.Company", "Company")
                        .WithMany("Devices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.LicenseRequest", b =>
                {
                    b.HasOne("Coliseu.Identity.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Coliseu.Identity.Domain.Entities.Partner", "Partner")
                        .WithMany("Requests")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.LicenseRequestModule", b =>
                {
                    b.HasOne("Coliseu.Identity.Domain.Entities.LicenseRequest", null)
                        .WithMany("Modules")
                        .HasForeignKey("LicenseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.Session", b =>
                {
                    b.HasOne("Coliseu.Identity.Domain.Entities.Device", "Device")
                        .WithMany("Sessions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.Company", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.Device", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.LicenseRequest", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.Partner", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Coliseu.Identity.Domain.Entities.PermissionGroup", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
