[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AQvPyIPTFIuPhFIFvIg2nQvsl0GCN5kUF8uO-BpO597I98-1piBUxUqq1cBdfiEBBx2SlTYyKD4-L9s7svp2U1uFx4V6z761tqLfGoWakyE55l6BDOXfD0Grj4ijNZXNwBpUp9HB5psCmG-w9rAANx5rNxjfaVoyl2BiLonP5sgruQmdmmxCAiUzse1n8yr6Kv7HoM4aCgYKAQESARYSFQHGX2MiolExTK2bqAwcFJi__gDCEw0206","token_type":"Bearer","refresh_token":"1//0hgZv41fAkYBPCgYIARAAGBESNwF-L9IrktHS1iTVKNTfO1MCGyyMCHFmvkdP3FMfwYVnq9DJRu7GadnXGj82PdQ_MhcEszeuH84","expiry":"2026-05-04T09:39:43.2262683-04:00","expires_in":3599}
root_folder_id = 1bnpoRNKR8UcxuEpPBKuqRjZyBbCqgP2t
