/* ============================================================================
   Diagnóstico SOMENTE LEITURA — base VetMatriz (Siscom/Firebird)
   Objetivo: mapear as tabelas que o Estoque Coliseu (conferência cega,
   separação/picking, romaneio) vai ler e gravar.

   Como rodar (IBExpert, FlameRobin ou isql) no Windows:
     1. Conecte em C:\PROJETOS COLISEU\Bancodedados\VetMatriz\VetMatriz.FDB
     2. Execute cada bloco e exporte o resultado (CSV ou copiar/colar).
     3. Nada aqui altera o banco: são apenas SELECTs. Termine com ROLLBACK.
   ============================================================================ */

SET TRANSACTION READ ONLY;

/* 1) Colunas das tabelas candidatas (uma linha por tabela) */
SELECT TRIM(rf.RDB$RELATION_NAME) AS tabela,
       LIST(TRIM(rf.RDB$FIELD_NAME) || ':' ||
            CASE f.RDB$FIELD_TYPE
              WHEN 7 THEN 'SMALLINT' WHEN 8 THEN 'INT' WHEN 16 THEN 'BIGINT'
              WHEN 10 THEN 'FLOAT' WHEN 27 THEN 'DOUBLE' WHEN 12 THEN 'DATE'
              WHEN 13 THEN 'TIME' WHEN 35 THEN 'TIMESTAMP'
              WHEN 14 THEN 'CHAR(' || f.RDB$FIELD_LENGTH || ')'
              WHEN 37 THEN 'VARCHAR(' || f.RDB$FIELD_LENGTH || ')'
              WHEN 261 THEN 'BLOB' ELSE 'T' || f.RDB$FIELD_TYPE END ||
            CASE WHEN f.RDB$FIELD_SCALE < 0 THEN '(dec' || (-f.RDB$FIELD_SCALE) || ')' ELSE '' END ||
            CASE WHEN rf.RDB$NULL_FLAG = 1 THEN '!' ELSE '' END, ', ') AS colunas
FROM RDB$RELATION_FIELDS rf
JOIN RDB$FIELDS f ON f.RDB$FIELD_NAME = rf.RDB$FIELD_SOURCE
WHERE rf.RDB$RELATION_NAME IN (
  'TBCONFCEGA','TBPICKINGUP','TBPICKRET','TBPICKRET2','TBPEDVENDAS','TBPEDIDOFV',
  'TBPEDVENC','TBPEDIDOLOG','TBROMANEIO','TBROMANEIO2','TBENDERECOPRODUTO',
  'TBREFERENCIA','TBSPKMOV','TBSPKNOTA','TBUSER','TBNOTASSAIDA','TBMOVESTOQUE',
  'TCADPRODUTO','TBSALDOATUAL','TBUNIDADEMEDIDA','TBLOTEPRODUTO','TBMOVLOTE',
  'TBFILIAIS','TBCADEMPRESA','TBTIPOMOVIMENTOSAIDA','TBSEQDOCTOS','TBCONFIG')
GROUP BY rf.RDB$RELATION_NAME
ORDER BY 1;

/* 2) Volume de cada tabela candidata */
SELECT 'TBCONFCEGA' t, COUNT(*) n FROM TBCONFCEGA UNION ALL
SELECT 'TBPICKINGUP', COUNT(*) FROM TBPICKINGUP UNION ALL
SELECT 'TBPICKRET', COUNT(*) FROM TBPICKRET UNION ALL
SELECT 'TBPICKRET2', COUNT(*) FROM TBPICKRET2 UNION ALL
SELECT 'TBPEDVENDAS', COUNT(*) FROM TBPEDVENDAS UNION ALL
SELECT 'TBPEDIDOFV', COUNT(*) FROM TBPEDIDOFV UNION ALL
SELECT 'TBROMANEIO', COUNT(*) FROM TBROMANEIO UNION ALL
SELECT 'TBROMANEIO2', COUNT(*) FROM TBROMANEIO2 UNION ALL
SELECT 'TBENDERECOPRODUTO', COUNT(*) FROM TBENDERECOPRODUTO UNION ALL
SELECT 'TBREFERENCIA', COUNT(*) FROM TBREFERENCIA UNION ALL
SELECT 'TBSPKMOV', COUNT(*) FROM TBSPKMOV UNION ALL
SELECT 'TBSPKNOTA', COUNT(*) FROM TBSPKNOTA;

/* 3) Chaves primárias e índices das tabelas candidatas */
SELECT TRIM(i.RDB$RELATION_NAME) tabela, TRIM(i.RDB$INDEX_NAME) indice,
       COALESCE(TRIM(rc.RDB$CONSTRAINT_TYPE), 'INDEX') tipo,
       LIST(TRIM(s.RDB$FIELD_NAME), ',') campos
FROM RDB$INDICES i
JOIN RDB$INDEX_SEGMENTS s ON s.RDB$INDEX_NAME = i.RDB$INDEX_NAME
LEFT JOIN RDB$RELATION_CONSTRAINTS rc ON rc.RDB$INDEX_NAME = i.RDB$INDEX_NAME
WHERE i.RDB$RELATION_NAME IN ('TBCONFCEGA','TBPICKINGUP','TBPICKRET','TBPICKRET2',
  'TBPEDVENDAS','TBROMANEIO','TBROMANEIO2','TBREFERENCIA','TBNOTASSAIDA','TBMOVESTOQUE')
GROUP BY 1, 2, 3
ORDER BY 1, 2;

/* 4) Triggers e procedures que já tocam conferência/picking/romaneio */
SELECT 'TRIGGER' tipo, TRIM(RDB$TRIGGER_NAME) nome, TRIM(RDB$RELATION_NAME) tabela
FROM RDB$TRIGGERS
WHERE COALESCE(RDB$SYSTEM_FLAG, 0) = 0
  AND RDB$RELATION_NAME IN ('TBCONFCEGA','TBPICKINGUP','TBPICKRET','TBPICKRET2','TBROMANEIO','TBROMANEIO2','TBPEDVENDAS')
UNION ALL
SELECT 'PROCEDURE', TRIM(RDB$PROCEDURE_NAME), NULL
FROM RDB$PROCEDURES
WHERE RDB$PROCEDURE_NAME CONTAINING 'CONF' OR RDB$PROCEDURE_NAME CONTAINING 'PICK'
   OR RDB$PROCEDURE_NAME CONTAINING 'ROMAN' OR RDB$PROCEDURE_NAME CONTAINING 'SEPAR';

/* 5) Amostra das 10 linhas mais recentes (só para entender o significado dos campos).
      Se alguma tabela não tiver coluna de data, rode só "SELECT FIRST 10 * FROM <tabela>". */
SELECT FIRST 10 * FROM TBCONFCEGA;
SELECT FIRST 10 * FROM TBPICKINGUP;
SELECT FIRST 10 * FROM TBPICKRET;
SELECT FIRST 10 * FROM TBROMANEIO;

/* 6) Como os pedidos aparecem em TBNOTASSAIDA por tipo de movimento (últimos 90 dias) */
SELECT n.CODTM, COUNT(*) qtd, MIN(n.DATAEMISSAO) de, MAX(n.DATAEMISSAO) ate
FROM TBNOTASSAIDA n
WHERE n.DATAEMISSAO >= CURRENT_DATE - 90
GROUP BY n.CODTM
ORDER BY 2 DESC;

ROLLBACK;
