-- ============================================================
-- Coliseu Speed Force — Schema Base Firebird 3.0
-- Script: 001_create_base_tables.sql
-- Executar com: isql -user SYSDBA -password masterkey
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- TABELA: SALES_ORDERS
-- Recebe pedidos enviados pelo app mobile via middleware.
-- ID = UUID v4 gerado no device (garante idempotência).
-- ─────────────────────────────────────────────────────────────

CREATE TABLE SALES_ORDERS (
  ID             VARCHAR(36)   NOT NULL,  -- UUID v4 do device
  COMPANY_ID     VARCHAR(36)   NOT NULL,  -- Multi-tenant
  CUSTOMER_ID    VARCHAR(36)   NOT NULL,
  SELLER_ID      VARCHAR(36)   NOT NULL,
  NATUREZA_ID    VARCHAR(36),             -- Natureza de operação selecionada (nullable por compatibilidade)
  STATUS         VARCHAR(20)   DEFAULT 'pending',
  TOTAL_AMOUNT   DECIMAL(15,2) NOT NULL,
  NOTES          VARCHAR(1000),
  CREATED_AT     TIMESTAMP     NOT NULL,
  UPDATED_AT     TIMESTAMP     NOT NULL,
  RECEIVED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_SALES_ORDERS PRIMARY KEY (ID)
);

-- Índices para consultas frequentes
CREATE INDEX IDX_SO_COMPANY_ID ON SALES_ORDERS (COMPANY_ID);
CREATE INDEX IDX_SO_SELLER_ID  ON SALES_ORDERS (SELLER_ID);
CREATE INDEX IDX_SO_STATUS     ON SALES_ORDERS (STATUS);
CREATE INDEX IDX_SO_CREATED_AT ON SALES_ORDERS (CREATED_AT);

-- ─────────────────────────────────────────────────────────────
-- TABELA: SALES_ORDER_ITEMS
-- Itens de cada pedido. Relacionada a SALES_ORDERS por ORDER_ID.
-- ─────────────────────────────────────────────────────────────

CREATE TABLE SALES_ORDER_ITEMS (
  ID               VARCHAR(36)    NOT NULL,  -- UUID v4 do device
  ORDER_ID         VARCHAR(36)    NOT NULL,
  PRODUCT_CODE     VARCHAR(50)    NOT NULL,
  PRODUCT_NAME     VARCHAR(200)   NOT NULL,
  QUANTITY         DECIMAL(10,3)  NOT NULL,
  UNIT_PRICE       DECIMAL(15,2)  NOT NULL,
  -- Desconto do item: armazena tanto o % quanto o valor absoluto para auditoria
  DISCOUNT_PERCENT DECIMAL(5,2)   DEFAULT 0,  -- Ex: 10.00 = 10%
  DISCOUNT_VALUE   DECIMAL(15,2)  DEFAULT 0,  -- Ex: 25.00 = R$ 25,00 de desconto
  TOTAL_PRICE      DECIMAL(15,2)  NOT NULL,   -- Já com desconto aplicado
  CONSTRAINT PK_SALES_ORDER_ITEMS PRIMARY KEY (ID),
  CONSTRAINT FK_SOI_ORDER FOREIGN KEY (ORDER_ID)
    REFERENCES SALES_ORDERS (ID)
);

CREATE INDEX IDX_SOI_ORDER_ID ON SALES_ORDER_ITEMS (ORDER_ID);

-- ─────────────────────────────────────────────────────────────
-- TABELA: SYNC_LOG
-- Registro de auditorias de sync. Útil para diagnóstico.
-- ─────────────────────────────────────────────────────────────

CREATE TABLE SYNC_LOG (
  ID             INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ORDER_UUID     VARCHAR(36)    NOT NULL,
  SELLER_ID      VARCHAR(36)    NOT NULL,
  ACTION         VARCHAR(20)    NOT NULL,  -- 'INSERT', 'DUPLICATE', 'ERROR'
  MESSAGE        VARCHAR(500),
  LOGGED_AT      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_SYNCLOG_ORDER ON SYNC_LOG (ORDER_UUID);
CREATE INDEX IDX_SYNCLOG_AT    ON SYNC_LOG (LOGGED_AT);

-- ─────────────────────────────────────────────────────────────
-- COMENTÁRIOS DE CONFIGURAÇÃO RECOMENDADA (firebird.conf)
--
-- MaxConnections = 30
-- DefaultDbCachePages = 8192
-- TempCacheLimit = 128M
-- DeadlockTimeout = 10
-- LockHashSlots = 8191
-- WireCrypt = Enabled
--
-- NUNCA desativar ForcedWrites em produção.
-- ─────────────────────────────────────────────────────────────
